package beatalbumshop;

import beatalbumshop.componment.MyDialog;
import beatalbumshop.componment.MyLabel;
import beatalbumshop.componment.MyNotification;
import beatalbumshop.dao.AlbumDAO;
import beatalbumshop.dao.AlbumDAOImpl;
import beatalbumshop.dao.CustomerDAO;
import beatalbumshop.dao.CustomerDAOImpl;
import beatalbumshop.model.Album;
import beatalbumshop.model.BagItem;
import beatalbumshop.model.Customer;
import beatalbumshop.model.LoggedInUser;
import beatalbumshop.model.Track;
import beatalbumshop.utils.ImageHelper;
import beatalbumshop.utils.OtherHelper;
import beatalbumshop.utils.TimeHelper;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.EmptyBorder;

public class AlbumDetail extends javax.swing.JPanel {

    AlbumDAO albumDAO = new AlbumDAOImpl();
    CustomerDAO customerDAO = new CustomerDAOImpl();
    String albumID;
    Album album;
    
    public AlbumDetail(String id) {
        initComponents();
        
        this.albumID = id;
        
        album = albumDAO.getByID(id + "");
        
        try {
            URL url = new URL("https://firebasestorage.googleapis.com/v0/b/beat-75a88.appspot.com/o/albums%2F" + album.getAlbumID() + ".png?alt=media");
            Image image = ImageIO.read(url);
            lblImage.setIcon(ImageHelper.resizing(image, 300, 300));
        } catch(Exception ex) {
            lblImage.setIcon(null);
            ex.printStackTrace();
        }

        lblName.setText("<html>" + album.getAlbumName() + "</html>");
        lblArtist.setText(album.getArtist());
        lblReleaseDate.setText(album.getReleaseDate());
        lblPrice.setText("$" + album.getPrice());
        
        cboQuantity.removeAllItems();
        for(int i = 1; i <= album.getInStock(); i++) {
            cboQuantity.addItem(i);
        }
        
        pnlTrackList.setLayout(new BoxLayout(pnlTrackList, BoxLayout.Y_AXIS));
        pnlTrackList.setBorder(new EmptyBorder(0, 20, 0, 20));

        // tracks
        ArrayList<Track> lTrack = new ArrayList<>();
        lTrack = album.getlTrack();
        for (Track track : lTrack) {
            JPanel pnl = new JPanel(new BorderLayout());
            pnl.setPreferredSize(new Dimension(545, 40));
            pnl.setMaximumSize(new Dimension(545, 40));
            pnl.setBackground(null);
            pnl.add(new MyLabel("<html>" + track.getTrackName() + "</html>"), BorderLayout.WEST);
            String duration = TimeHelper.msToMinute(track.getDurationMS() + "");
            pnl.add(new MyLabel(duration), BorderLayout.EAST);
            pnlTrackList.add(pnl);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlContent = new javax.swing.JPanel();
        lblImage = new beatalbumshop.componment.MyLabel();
        lblName = new beatalbumshop.componment.MyLabel();
        lblArtist = new beatalbumshop.componment.MyLabel();
        lblReleaseDate = new beatalbumshop.componment.MyLabel();
        lblPrice = new beatalbumshop.componment.MyLabel();
        myScrollPane1 = new beatalbumshop.componment.MyScrollPane();
        pnlTrackList = new javax.swing.JPanel();
        btnBuyNow = new beatalbumshop.componment.MyButton();
        btnAddToBag = new beatalbumshop.componment.MyButton();
        cboQuantity = new beatalbumshop.componment.MyComboBox();
        lblQuantity = new beatalbumshop.componment.MyLabel();
        btnClose = new beatalbumshop.componment.MyButton();

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));

        lblName.setText("30");
        lblName.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N

        lblArtist.setForeground(new java.awt.Color(80, 80, 80));
        lblArtist.setText("Adele");

        lblReleaseDate.setForeground(new java.awt.Color(80, 80, 80));
        lblReleaseDate.setText("2021-10-15");

        lblPrice.setForeground(new java.awt.Color(80, 80, 80));
        lblPrice.setText("$ 33");

        myScrollPane1.setBorder(null);
        myScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlTrackList.setBackground(new java.awt.Color(255, 255, 255));
        pnlTrackList.setMaximumSize(new java.awt.Dimension(408, 414));

        javax.swing.GroupLayout pnlTrackListLayout = new javax.swing.GroupLayout(pnlTrackList);
        pnlTrackList.setLayout(pnlTrackListLayout);
        pnlTrackListLayout.setHorizontalGroup(
            pnlTrackListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        pnlTrackListLayout.setVerticalGroup(
            pnlTrackListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        myScrollPane1.setViewportView(pnlTrackList);

        btnBuyNow.setBackground(new java.awt.Color(0, 162, 47));
        btnBuyNow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 162, 47)));
        btnBuyNow.setForeground(new java.awt.Color(255, 255, 255));
        btnBuyNow.setText("Buy Now");
        btnBuyNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNowActionPerformed(evt);
            }
        });

        btnAddToBag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddToBag.setText("Add to Bag");
        btnAddToBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToBagActionPerformed(evt);
            }
        });

        cboQuantity.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 5)));
        cboQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2" }));
        cboQuantity.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        lblQuantity.setForeground(new java.awt.Color(80, 80, 80));
        lblQuantity.setText("Quantity:");

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblArtist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(myScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddToBag, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuyNow, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(btnBuyNow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlContentLayout.createSequentialGroup()
                            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(myScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlContentLayout.createSequentialGroup()
                                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lblArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lblReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddToBag, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlContentLayout.createSequentialGroup()
                            .addGap(446, 446, 446)
                            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        btnClose.setBackground(null);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beatalbumshop/resources/images/icons/back.png"))); // NOI18N
        btnClose.setPreferredSize(new java.awt.Dimension(70, 50));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        Main mainFrame = OtherHelper.getMainFrame(this);
        mainFrame.getBtnShop().doClick();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnBuyNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNowActionPerformed
        if (!LoggedInUser.isLoggedIn() || !LoggedInUser.isCustomer()) {
            new LogIn().setVisible(true);
            MyDialog.display(1, "Bạn phải đăng nhập trước khi sử dụng tính năng này");
        }
        else {
            System.out.println("ok");
        }
    }//GEN-LAST:event_btnBuyNowActionPerformed

    private void btnAddToBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToBagActionPerformed
        if (!LoggedInUser.isLoggedIn() || !LoggedInUser.isCustomer()) {
            new LogIn().setVisible(true);
            MyDialog.display(1, "Bạn phải đăng nhập trước khi sử dụng tính năng này");
        }
        else {
            Customer customer = (Customer) LoggedInUser.getCurrentUser();
            ArrayList<BagItem> lBagItem = customer.getlBagItem();
            
            //check exist
            boolean added = false;
            boolean error = false; // false = kh add
            int q = Integer.parseInt(cboQuantity.getSelectedItem().toString()); // so tren combobox
            
            for(BagItem item : lBagItem) {
                // kiem tra ton tai trong bag
                if(item.getAlbumID().equals(albumID)) {
                    // da ton tai
                    if(album.getInStock() < item.getQuantity() + q) {
                        // them > instock
                        MyNotification n = new MyNotification((JFrame) SwingUtilities.getWindowAncestor(this), true, "Currently not available");
                        n.setVisible(true);
                        error = true;
                    }
                    else {
                        item.setQuantity(item.getQuantity() + q);   
                    }
                    
                    added = true;
                    break;
                }
            }
            
            if(!added) {
                lBagItem.add(new BagItem(albumID, q));
                added = true;
            }
            
            if(!error) {
                // +1 hoac them moi
                customer.setlBagItem(lBagItem);
                boolean result = customerDAO.updateByID(customer);
                if(result && added) {
                    LoggedInUser.setCurrentLoggedIn(customer); //update
                    MyNotification n = new MyNotification((JFrame) SwingUtilities.getWindowAncestor(this), true, "Added to Bag");
                    n.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btnAddToBagActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private beatalbumshop.componment.MyButton btnAddToBag;
    private beatalbumshop.componment.MyButton btnBuyNow;
    private beatalbumshop.componment.MyButton btnClose;
    private beatalbumshop.componment.MyComboBox cboQuantity;
    private beatalbumshop.componment.MyLabel lblArtist;
    private beatalbumshop.componment.MyLabel lblImage;
    private beatalbumshop.componment.MyLabel lblName;
    private beatalbumshop.componment.MyLabel lblPrice;
    private beatalbumshop.componment.MyLabel lblQuantity;
    private beatalbumshop.componment.MyLabel lblReleaseDate;
    private beatalbumshop.componment.MyScrollPane myScrollPane1;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTrackList;
    // End of variables declaration//GEN-END:variables
}
