package beatalbumshop;

import beatalbumshop.dao.CustomerDAO;
import beatalbumshop.dao.CustomerDAOImpl;
import beatalbumshop.dao.OrderDAO;
import beatalbumshop.dao.OrderDAOImpl;
import beatalbumshop.model.Order;
import beatalbumshop.utils.ChartHelper;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JPanel;

public class Dashboard extends javax.swing.JPanel {
    
    OrderDAO orderDAO = new OrderDAOImpl();
    CustomerDAO customerDAO = new CustomerDAOImpl();
    ArrayList<Double> lColValue = new ArrayList<>();
    ArrayList<Order> lOrder = new ArrayList<>();

    public Dashboard() {
        initComponents();
        
        lOrder = (ArrayList) orderDAO.getAll();
        display();
    }
    
    
    
    public void display() {
        
        Double totalSale = 0.0;
        int totalOrder = 0;
        int totalCustomer = 0;
        
        //chart
        ArrayList<String> lColName = new ArrayList<>();
        //get last 7 day
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd ");
        Calendar cal = Calendar.getInstance().getInstance();
        // get starting date
        cal.add(Calendar.DAY_OF_YEAR, -6);

        // loop adding one day in each iteration
        for(int i = 0; i <= 6; i++){
            cal.add(Calendar.DAY_OF_YEAR, 1);
            lColName.add(sdf.format(cal.getTime()).trim());
        }
        
        //lbl
        for(Order order : lOrder) {
            totalSale += order.getTotal();
            totalOrder++;
        }
        lblTotalSale.setText("$" + totalSale);
        lblTotalOrder.setText(totalOrder + "");
        lblTotalCustomer.setText(customerDAO.getAll().size() + "");
        
        //chart
        for(String d : lColName) {
            int flag = 0;
            Double t = 0.0;
            for(Order o : lOrder) {
                if(o.getDate().equals(d)) { 
                    t += o.getTotal();
                    flag = 1;
                }
            }
            
            if(flag == 0) lColValue.add(0.0);
            else lColValue.add(t);
        }
        
        JPanel pnl = new JPanel();
        pnl.setPreferredSize(new Dimension(0, pnlChart.getPreferredSize().height));

        ChartHelper.createChart(lColValue, lColName, pnl);

        pnlChart.add(pnl, BorderLayout.CENTER);
        pnlChart.revalidate();
        pnlChart.repaint();
    }
    
    
    
    public Double getTotalOneDay(String d) {
        Double total = 0.0;
        
        for(Order o : lOrder) {
            if(o.getDate().equals(d)) {
                total += o.getTotal();
            }
        }
        
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlTotalSale = new javax.swing.JPanel();
        lblTotalSale2 = new beatalbumshop.componment.MyLabel();
        lblTotalSale = new beatalbumshop.componment.MyLabel();
        lblTotalSaleIcon = new beatalbumshop.componment.MyLabel();
        lblTotalSale8 = new beatalbumshop.componment.MyLabel();
        pnlTotalSale1 = new javax.swing.JPanel();
        lblTotalSale3 = new beatalbumshop.componment.MyLabel();
        lblTotalOrder = new beatalbumshop.componment.MyLabel();
        lblTotalSaleIcon1 = new beatalbumshop.componment.MyLabel();
        lblTotalSale7 = new beatalbumshop.componment.MyLabel();
        pnlTotalSale2 = new javax.swing.JPanel();
        lblTotalSale4 = new beatalbumshop.componment.MyLabel();
        lblTotalCustomer = new beatalbumshop.componment.MyLabel();
        lblTotalSaleIcon2 = new beatalbumshop.componment.MyLabel();
        lblTotalSale6 = new beatalbumshop.componment.MyLabel();
        jPanel1 = new javax.swing.JPanel();
        lblChartTitle = new beatalbumshop.componment.MyLabel();
        pnlChart = new javax.swing.JPanel();

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        pnlTotalSale.setBackground(new java.awt.Color(255, 255, 255));
        pnlTotalSale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotalSale2.setText("Total Sales:");

        lblTotalSale.setText("$00000");
        lblTotalSale.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N

        lblTotalSaleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beatalbumshop/resources/images/icons/sale-48x48.png"))); // NOI18N

        lblTotalSale8.setText("(this month)");
        lblTotalSale8.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlTotalSaleLayout = new javax.swing.GroupLayout(pnlTotalSale);
        pnlTotalSale.setLayout(pnlTotalSaleLayout);
        pnlTotalSaleLayout.setHorizontalGroup(
            pnlTotalSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalSaleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlTotalSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalSale, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTotalSaleLayout.createSequentialGroup()
                        .addComponent(lblTotalSale2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalSale8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblTotalSaleIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlTotalSaleLayout.setVerticalGroup(
            pnlTotalSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalSaleLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlTotalSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTotalSaleIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTotalSaleLayout.createSequentialGroup()
                        .addGroup(pnlTotalSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalSale2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalSale8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTotalSale1.setBackground(new java.awt.Color(255, 255, 255));
        pnlTotalSale1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotalSale3.setText("Total Orders:");

        lblTotalOrder.setText("$00000");
        lblTotalOrder.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N

        lblTotalSaleIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beatalbumshop/resources/images/icons/order-48x48.png"))); // NOI18N

        lblTotalSale7.setText("(this month)");
        lblTotalSale7.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlTotalSale1Layout = new javax.swing.GroupLayout(pnlTotalSale1);
        pnlTotalSale1.setLayout(pnlTotalSale1Layout);
        pnlTotalSale1Layout.setHorizontalGroup(
            pnlTotalSale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalSale1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlTotalSale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTotalSale1Layout.createSequentialGroup()
                        .addComponent(lblTotalSale3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalSale7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblTotalSaleIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlTotalSale1Layout.setVerticalGroup(
            pnlTotalSale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalSale1Layout.createSequentialGroup()
                .addGroup(pnlTotalSale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTotalSale1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlTotalSale1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalSale3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalSale7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTotalSale1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalSaleIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        pnlTotalSale2.setBackground(new java.awt.Color(255, 255, 255));
        pnlTotalSale2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotalSale4.setText("Total Customers:");

        lblTotalCustomer.setText("$00000");
        lblTotalCustomer.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N

        lblTotalSaleIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beatalbumshop/resources/images/icons/customer-48x48.png"))); // NOI18N

        lblTotalSale6.setText("(this month)");
        lblTotalSale6.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlTotalSale2Layout = new javax.swing.GroupLayout(pnlTotalSale2);
        pnlTotalSale2.setLayout(pnlTotalSale2Layout);
        pnlTotalSale2Layout.setHorizontalGroup(
            pnlTotalSale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalSale2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlTotalSale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTotalSale2Layout.createSequentialGroup()
                        .addComponent(lblTotalSale4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalSale6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lblTotalSaleIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlTotalSale2Layout.setVerticalGroup(
            pnlTotalSale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalSale2Layout.createSequentialGroup()
                .addGroup(pnlTotalSale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTotalSale2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlTotalSale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalSale4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalSale6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTotalSale2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalSaleIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(978, 475));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lblChartTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        lblChartTitle.setText("Sales Statistic");
        lblChartTitle.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        jPanel1.add(lblChartTitle, java.awt.BorderLayout.PAGE_START);

        pnlChart.setBackground(new java.awt.Color(240, 240, 240));
        pnlChart.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 199, 199)), javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 20)));
        pnlChart.setMinimumSize(new java.awt.Dimension(412, 264));
        pnlChart.setPreferredSize(new java.awt.Dimension(412, 190));
        pnlChart.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlChart, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlTotalSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(pnlTotalSale1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(pnlTotalSale2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTotalSale1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTotalSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTotalSale2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private beatalbumshop.componment.MyLabel lblChartTitle;
    private beatalbumshop.componment.MyLabel lblTotalCustomer;
    private beatalbumshop.componment.MyLabel lblTotalOrder;
    private beatalbumshop.componment.MyLabel lblTotalSale;
    private beatalbumshop.componment.MyLabel lblTotalSale2;
    private beatalbumshop.componment.MyLabel lblTotalSale3;
    private beatalbumshop.componment.MyLabel lblTotalSale4;
    private beatalbumshop.componment.MyLabel lblTotalSale6;
    private beatalbumshop.componment.MyLabel lblTotalSale7;
    private beatalbumshop.componment.MyLabel lblTotalSale8;
    private beatalbumshop.componment.MyLabel lblTotalSaleIcon;
    private beatalbumshop.componment.MyLabel lblTotalSaleIcon1;
    private beatalbumshop.componment.MyLabel lblTotalSaleIcon2;
    private javax.swing.JPanel pnlChart;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTotalSale;
    private javax.swing.JPanel pnlTotalSale1;
    private javax.swing.JPanel pnlTotalSale2;
    // End of variables declaration//GEN-END:variables
}
