package beatalbumshop;

import beatalbumshop.componment.MyDialog;
import beatalbumshop.model.LoggedInUser;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JButton;

public class MainAdmin extends javax.swing.JFrame {
    JButton [] btnMenuList;
    Color gray = new Color(50, 50, 50);

    public MainAdmin() {
        initComponents();
        
        // rounded frame
        setShape(new RoundRectangle2D.Double(0, 0, 1280, 720, 20, 20));
        setSize(1280, 720);
        setLocationRelativeTo(null);
        
        // tab
        pnlTabContent.setLayout(new CardLayout());
        pnlTabContent.add(new ManagementAlbum(), "album");
        pnlTabContent.add(new ManagementCustomer(), "customer");
        pnlTabContent.add(new ManagementOrder(), "order");
        pnlTabContent.add(new ManagementUser(), "user");
        pnlTabContent.add(new ManagementReport(), "report");
        pnlTabContent.add(new Account(), "account");
        
        btnMenuList = new JButton[] {btnAlbum, btnCustomer, btnOrder, btnUser, btnReport, btnLogIn};
        for(JButton btn : btnMenuList) {
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // mau chu
                    for(JButton btn : btnMenuList) {
                        btn.setForeground(gray);
                    }
                    JButton b = (JButton)e.getSource();
                    b.setForeground(Color.BLACK);
                    
                    // show tab
                    String name = e.getActionCommand().toLowerCase().replaceAll(" ", "");
                    CardLayout c = (CardLayout) pnlTabContent.getLayout();
                    c.show(pnlTabContent, name);
                }
            });
        }
        
        
        // Check login
        if (LoggedInUser.isLoggedIn()) {
            btnLogIn.setText("Account");
        }
        
        //check admin or staff
        if(LoggedInUser.isStaff()) {
            btnUser.setVisible(false);
            btnReport.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        windowTitleBar = new beatalbumshop.componment.WindowTitleBar();
        pnlSideBar = new javax.swing.JPanel();
        btnAlbum = new beatalbumshop.componment.MyButton();
        btnCustomer = new beatalbumshop.componment.MyButton();
        btnOrder = new beatalbumshop.componment.MyButton();
        btnUser = new beatalbumshop.componment.MyButton();
        btnReport = new beatalbumshop.componment.MyButton();
        btnLogIn = new beatalbumshop.componment.MyButton();
        pnlTabContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beat To Beat");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlMain.setLayout(new java.awt.BorderLayout());

        windowTitleBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        windowTitleBar.setFrame(this);
        pnlMain.add(windowTitleBar, java.awt.BorderLayout.PAGE_START);

        pnlSideBar.setBackground(new java.awt.Color(255, 255, 255));
        pnlSideBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        pnlSideBar.setPreferredSize(new java.awt.Dimension(250, 658));
        pnlSideBar.setLayout(new javax.swing.BoxLayout(pnlSideBar, javax.swing.BoxLayout.Y_AXIS));

        btnAlbum.setBackground(null);
        btnAlbum.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 20, 0, 0));
        btnAlbum.setText("Album");
        btnAlbum.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnAlbum.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAlbum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlbum.setMargin(new java.awt.Insets(20, 20, 3, 14));
        btnAlbum.setMaximumSize(new java.awt.Dimension(248, 50));
        btnAlbum.setMinimumSize(new java.awt.Dimension(248, 50));
        btnAlbum.setPreferredSize(new java.awt.Dimension(248, 46));
        pnlSideBar.add(btnAlbum);

        btnCustomer.setBackground(null);
        btnCustomer.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 20, 0, 0));
        btnCustomer.setText("Customer");
        btnCustomer.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustomer.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnCustomer.setMaximumSize(new java.awt.Dimension(248, 50));
        btnCustomer.setMinimumSize(new java.awt.Dimension(248, 50));
        pnlSideBar.add(btnCustomer);

        btnOrder.setBackground(null);
        btnOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 20, 0, 0));
        btnOrder.setText("Order");
        btnOrder.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrder.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnOrder.setMaximumSize(new java.awt.Dimension(248, 50));
        btnOrder.setMinimumSize(new java.awt.Dimension(248, 50));
        pnlSideBar.add(btnOrder);

        btnUser.setBackground(null);
        btnUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 20, 0, 0));
        btnUser.setText("User");
        btnUser.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnUser.setMaximumSize(new java.awt.Dimension(248, 50));
        btnUser.setMinimumSize(new java.awt.Dimension(248, 50));
        pnlSideBar.add(btnUser);

        btnReport.setBackground(null);
        btnReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 20, 0, 0));
        btnReport.setText("Report");
        btnReport.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReport.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnReport.setMaximumSize(new java.awt.Dimension(248, 50));
        btnReport.setMinimumSize(new java.awt.Dimension(248, 50));
        pnlSideBar.add(btnReport);

        btnLogIn.setBackground(null);
        btnLogIn.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 20, 0, 0));
        btnLogIn.setText("Log In");
        btnLogIn.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnLogIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogIn.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnLogIn.setMaximumSize(new java.awt.Dimension(248, 50));
        btnLogIn.setMinimumSize(new java.awt.Dimension(248, 50));
        pnlSideBar.add(btnLogIn);

        pnlMain.add(pnlSideBar, java.awt.BorderLayout.LINE_START);

        pnlTabContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabContent.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlTabContentLayout = new javax.swing.GroupLayout(pnlTabContent);
        pnlTabContent.setLayout(pnlTabContentLayout);
        pnlTabContentLayout.setHorizontalGroup(
            pnlTabContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        pnlTabContentLayout.setVerticalGroup(
            pnlTabContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );

        pnlMain.add(pnlTabContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnAlbum.doClick();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Check login
                if (!LoggedInUser.isAdmin()) {
                    new LogIn().setVisible(true);
                    MyDialog.display(1, "Bạn phải đăng nhập đúng role để có thể tiếp tục truy cập chức năng này");
                }
                else {
                    new MainAdmin().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private beatalbumshop.componment.MyButton btnAlbum;
    private beatalbumshop.componment.MyButton btnCustomer;
    private beatalbumshop.componment.MyButton btnLogIn;
    private beatalbumshop.componment.MyButton btnOrder;
    private beatalbumshop.componment.MyButton btnReport;
    private beatalbumshop.componment.MyButton btnUser;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSideBar;
    private javax.swing.JPanel pnlTabContent;
    private beatalbumshop.componment.WindowTitleBar windowTitleBar;
    // End of variables declaration//GEN-END:variables
}
