package beatalbumshop;

import beatalbumshop.componment.MyButton;
import beatalbumshop.componment.MyComboBox;
import beatalbumshop.dao.CustomerDAO;
import beatalbumshop.dao.CustomerDAOImpl;
import beatalbumshop.model.Album;
import beatalbumshop.model.BagItem;
import beatalbumshop.model.Customer;
import beatalbumshop.model.LoggedInUser;
import beatalbumshop.utils.ImageHelper;
import beatalbumshop.utils.OtherHelper;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.net.URL;
import java.util.ArrayList;
import javax.imageio.ImageIO;

public class SelectionProduct extends javax.swing.JPanel {
    CustomerDAO customerDAO = new CustomerDAOImpl();
    Customer customer = (Customer) LoggedInUser.getCurrentUser();
    String albumID;
    double price;
    long quantity;

    public SelectionProduct(Album album, long quantity) {
        initComponents();

        this.albumID = album.getAlbumID();
        this.price = album.getPrice();
        this.quantity = quantity;
        
        Image image = null;
        try {
            URL url = new URL("https://firebasestorage.googleapis.com/v0/b/beat-75a88.appspot.com/o/albums%2F" + album.getAlbumID() + ".png?alt=media");
            image = ImageIO.read(url);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        lblImage.setIcon(ImageHelper.resizing(image, 80, 80));
        lblAlbumName.setText("<html>" + album.getAlbumName() + "</html>");
        lblArtist.setText(album.getArtist());
        lblPrice.setText("$ " + album.getPrice());
        
        cboQuantity.removeAllItems();
        // quantity > instock
        if(quantity > album.getInStock()) {
            quantity = album.getInStock();
        }
        
        for(int i = 1; i <= album.getInStock(); i++) {
            cboQuantity.addItem(i);
            if(i == quantity) cboQuantity.setSelectedItem(i);
        }
    }
    
    
    
    public double getSubtotal() {
        return price * quantity;
    }
    
    
    
    public MyButton getBthRemove() {
        return btnRemove;
    }
    
    public MyComboBox getCboQuantity() {
        return cboQuantity;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblImage = new beatalbumshop.componment.MyLabel();
        lblAlbumName = new beatalbumshop.componment.MyLabel();
        lblArtist = new beatalbumshop.componment.MyLabel();
        lblPrice = new beatalbumshop.componment.MyLabel();
        cboQuantity = new beatalbumshop.componment.MyComboBox();
        btnRemove = new beatalbumshop.componment.MyButton();

        setMaximumSize(new java.awt.Dimension(571, 100));
        setPreferredSize(new java.awt.Dimension(571, 100));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        lblAlbumName.setText("30");

        lblArtist.setText("Adele");
        lblArtist.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        lblPrice.setText("$ 11");
        lblPrice.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        cboQuantity.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 5)));
        cboQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2" }));
        cboQuantity.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        cboQuantity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboQuantityItemStateChanged(evt);
            }
        });

        btnRemove.setBackground(null);
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beatalbumshop/resources/images/icons/close-16x16.png"))); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblArtist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAlbumName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(cboQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(lblAlbumName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(lblArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16))
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        ArrayList<BagItem> lBagItem = customer.getlBagItem();
        for(BagItem item : lBagItem) {
            if(item.getAlbumID().equals(albumID)) {
                lBagItem.remove(item);
                ShoppingBag sp = new ShoppingBag();
                sp.getlBagItem().remove(item);
                break;
            }
        }
        
        customer.setlBagItem(lBagItem);
        customerDAO.updateByID(customer);
        
        // click to reset
        Main m = OtherHelper.getMainFrame(this);
        m.getBtnShoppingBag().doClick();
    }//GEN-LAST:event_btnRemoveActionPerformed

    
    
    private void cboQuantityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboQuantityItemStateChanged
        //vi khi chay se bao gom SELECTED va DESELECTED
        if (evt.getStateChange() == ItemEvent.SELECTED && OtherHelper.getMainFrame(this) != null) {
            int q = Integer.parseInt(cboQuantity.getSelectedItem().toString()); // so tren combobox
            
            ArrayList<BagItem> lBagItem = customer.getlBagItem();
            for(BagItem item : lBagItem) {
                if(item.getAlbumID().equals(albumID)) {
                    item.setQuantity(q);
                    break;
                }
            }

            customer.setlBagItem(lBagItem);
            customerDAO.updateByID(customer);

            // click to reset
            Main m = OtherHelper.getMainFrame(this);
            m.getBtnShoppingBag().doClick();
        }
    }//GEN-LAST:event_cboQuantityItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private beatalbumshop.componment.MyButton btnRemove;
    private beatalbumshop.componment.MyComboBox cboQuantity;
    private beatalbumshop.componment.MyLabel lblAlbumName;
    private beatalbumshop.componment.MyLabel lblArtist;
    private beatalbumshop.componment.MyLabel lblImage;
    private beatalbumshop.componment.MyLabel lblPrice;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
